trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- name: BuildConfiguration
  value: Release
- name: BuildPlatform
  value: x64
- name: AppPackageLocation
  value: $(Build.ArtifactStagingDirectory)/applicationpackage

steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore Packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
        vstsFeed: 'PRIVATE_FEED_GUID'
        includeNuGetOrg: false
    - task: NuGetCommand@2
      displayName: Restore packages
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sfproj'
        feedsToUse: 'select'
        vstsFeed: 'PRIVATE_FEED_GUID'
        includeNuGetOrg: false
        restoreDirectory: packages
    - task: VSBuild@1
      displayName: 'Build solution (release)'
      enabled: false
      inputs:
        solution: '**\*.sln'
        vsVersion: latest
        platform: '$(BuildPlatform)'
        configuration: $(BuildConfiguration)
        clean: true
    - task: VSBuild@1
      displayName: 'Build solution for Service Fabric'
      inputs:
        solution: '**\*.sfproj'
        vsVersion: latest
        msbuildArgs: '/t:Package /p:PackageLocation=$(AppPackageLocation)'
        platform: '$(BuildPlatform)'
        configuration: $(BuildConfiguration)
    - task: ServiceFabricUpdateManifests@2
      displayName: 'Update Service Fabric Manifest Versions'
      inputs:
        applicationPackagePath: '$(AppPackageLocation)'
        versionSuffix: '$(Build.BuildNumber)'
        versionBehavior: Replace
        updateOnlyChanged: true
        pkgArtifactName: drop