trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 5.0.x
    performMultiLevelLookup: true
    includePreviewVersions: true

- task: UseDotNet@2
  displayName: 'Install .NET Runtime'
  inputs:
    version: '3.0.x'
    packageType: runtime

- task: DotNetCoreCLI@2
  displayName: Restoring Dependencies
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    custom: '/p:PublishSingleFile=true /p:PublishTrimmed=true'
    vstsFeed: 'my-vsts-feed'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    custom: '/p:PublishSingleFile=true /p:PublishTrimmed=true'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: False
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    custom: '/p:PublishSingleFile=true /p:PublishTrimmed=true'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: Send Artifact
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'Dexter'